/**
 * Bundle the notification sound effects into an injectable script.
 *
 * The sources are the 45 UI alert sounds shipped by opencode
 * (https://github.com/anomalyco/opencode, MIT — see crates/dsh-gui/audio/
 * README.md). They are embedded as `data:audio/mpeg` URIs so the webview can
 * play them without any extra server, protocol handler, or file access.
 *
 * Usage: node scripts/make-audio.mjs
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const audioDir = join(root, 'crates', 'dsh-gui', 'audio')
const outFile = join(root, 'crates', 'dsh-gui', 'src', 'audio.js')

// Stable option order: matches opencode's SOUND_OPTIONS grouping.
const GROUPS = [
  { prefix: 'alert-', count: 10 },
  { prefix: 'bip-bop-', count: 10 },
  { prefix: 'staplebops-', count: 7 },
  { prefix: 'nope-', count: 12 },
  { prefix: 'yup-', count: 6 },
]

const ids = []
for (const group of GROUPS) {
  for (let n = 1; n <= group.count; n += 1) {
    ids.push(`${group.prefix}${String(n).padStart(2, '0')}`)
  }
}

let bytes = 0
const entries = []
for (const id of ids) {
  const file = join(audioDir, `${id}.mp3`)
  const payload = readFileSync(file)
  bytes += payload.length
  entries.push(`  ${JSON.stringify(id)}: "data:audio/mpeg;base64,${payload.toString('base64')}",`)
}

if (readdirSync(audioDir).some((name) => name.endsWith('.mp3') && !ids.includes(name.replace(/\.mp3$/, '')))) {
  throw new Error('make-audio: unexpected mp3 in crates/dsh-gui/audio; extend GROUPS first')
}

const header = `\
/**
 * GENERATED by scripts/make-audio.mjs — do not edit by hand.
 *
 * Notification sound effects (opencode MIT, see crates/dsh-gui/audio/README.md),
 * embedded as data: URIs so notify.js can play them with a plain Audio element.
 */
`

const script = `${header}(function () {
  'use strict'
  window.__DSH_GUI_AUDIO__ = {
${entries.join('\n')}
  }
})()
`
writeFileSync(outFile, script)
console.log(`make-audio: ${ids.length} sounds (${(bytes / 1024).toFixed(0)} KB raw) -> ${outFile} (${(statSync(outFile).size / 1024).toFixed(0)} KB)`)
